project_id = "sqbdwdncojtlafagotcb"

[functions.create-checkout]
verify_jwt = true

[functions.send-otp-email]
verify_jwt = false

[auth.hook.send_email]
enabled = true
uri = "https://sqbdwdncojtlafagotcb.supabase.co/functions/v1/send-otp-email"
secrets = ["SEND_EMAIL_HOOK_SECRET"]